### ISSUE TITLE
Allow predefined selectors

### ISSUE THREAD

**Issue by kuanf** [turbonomic/orm#29]
The duplicated long list of label selector to address different path with same group of owned resource looks clumsy. I think we can allow predefined selector (like parameters) to be reused. something like this:

```yaml
...
spec:
...
  mappings:
    selectors:
      core: 
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - action-orchestrator
          - api
          - auth
          - clustermgr
          ...
    patterns:
    - ownerPath: .spec.{{.owned.name}}.resources
      owned:
        path: .spec.template.spec.containers[?(@.name=="{{.owned.name}}")].resources
        apiVersion: apps/v1
        kind: Deployment
        selector: core
    - ownerPath: .spec.{{.owned.name}}.replicaCount
      owned:
        path: .spec.replicas
        apiVersion: apps/v1
        kind: Deployment
        selector: core    
```
