### ISSUE TITLE
escape dot in jsonpath

### ISSUE THREAD

**Issue by kuanf** [turbonomic/orm#40]
Use case 1 - labels:

```yaml
metadata:
  labels:
    "ibm.com/type": "app"
```

Use case 2 - special field:

```yaml
spec:
  components:
    ibm.com:
      websphere:
        resources:
```

In order to work with fields with dot in the key, we can't use jsonpath like `.metadata.labels.ibm.com/type` or `.spec.ibm.com.websphere.resources`

According to evaluator from https://jsonpath.com/

the right way is to use `.metadata.labels.['ibm.com/type']` `.spec.['ibm.com'].websphere.resources`

we need to support that approach.
